-- Create User table

CREATE TABLE USERS (
    ID INTEGER NOT NULL PRIMARY KEY auto_increment,
    
    email VARCHAR(50) NOT NULL,
   
    password_hash VARCHAR(50) NOT NULL,
   
    Created_at DATETIME NOT NULL,
    UNIQUE INDEX uq_email (email ASC)
);

CREATE TABLE POST (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INTEGER NOT NULL,
  content TEXT NOT NULL,
  picture_path TEXT NOT NULL,
  created_at DATETIME NOT NULL,
  FOREIGN KEY (user_id) REFERENCES USERS (ID)
);

CREATE TABLE COMMENT (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  COMMENT_TEXT TEXT NOT NULL,
  POSTID INTEGER NOT NULL,
  userId INTEGER NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (POSTID) REFERENCES POST (id),
  FOREIGN KEY (userId) REFERENCES USERS (ID)
);


CREATE TABLE LIKES (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  postId INTEGER NOT NULL,
  userId INTEGER NOT NULL,
  FOREIGN KEY (postId) REFERENCES POST(id),
  FOREIGN KEY (userId) REFERENCES USERS (ID)
);



-- Create Artwork table
CREATE TABLE Artwork (
    ArtworkID INT PRIMARY KEY,
    ArtistID INT,
    Title VARCHAR(255) NOT NULL,
    Description TEXT,
    Image VARCHAR(255),
    Price DECIMAL(10,2),
    FOREIGN KEY (ArtistID) REFERENCES Artist(ArtistID)
);

-- Create View table
CREATE TABLE View (
    ViewID INT PRIMARY KEY,
    UserID INT,
    ViewName VARCHAR(255) NOT NULL,
    FOREIGN KEY (UserID) REFERENCES User(UserID)
);

